r"""
D:\Tiktok\models\events\base.py

Core Definitions for the Event-Driven Social Analysis Framework.
This module defines the fundamental data structures and interfaces for the simulation.

Key Concept: The L-T-I-C-P Event Model
--------------------------------------
Every event in the system is defined by a 5-dimensional tuple:
1. Location (L): Where it happens (Spatial coordinates).
2. Time (T): When it starts (Temporal timestamp).
3. Intensity (I): The peak magnitude/impact (S_max).
4. Content (C): The semantic topic vector (Embedding).
5. Polarity (P): The controversial nature of the event (Consensus vs. Polarization).

Design Philosophy:
------------------
- Decoupling Data & Logic: The `Event` class is a data container. The logic for 
  how it decays or influences agents is handled by the Engine using the 
  `spatial_params` and `temporal_params` carried by the event.
- Heterogeneity: Events carry their own diffusion parameters (generated by distributions),
  allowing the system to simulate both "flash mobs" (fast decay) and "lingering issues".
"""

from dataclasses import dataclass, field
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
import numpy as np

# =========================================================================
# 1. The Event Entity
# =========================================================================

@dataclass
class Event:
    """
    Represents a discrete spatiotemporal event based on the L-T-I-C-P model.
    """
    
    # --- Identity ---
    uid: int
    """Unique Identifier for the event."""

    # --- L-T-I-C-P Attributes ---
    
    # 1. Location (L)
    loc: np.ndarray
    """
    Coordinate vector [x, y].
    Assumes normalized map coordinates [0, 1] or grid indices depending on config.
    """

    # 2. Time (T)
    time: float
    """Start timestamp of the event."""

    # 3. Intensity (I)
    intensity: float
    """
    The peak impact value (S_max). 
    Typically sampled from a Power-law (Pareto) distribution.
    """

    # 4. Content (C)
    content: np.ndarray
    """
    Topic vector of shape (n_layers,). 
    Represents the semantic category (e.g., [Political, Entertainment, Sports]).
    """

    # 5. Polarity (P)
    polarity: float
    """
    Controversy factor in range [-1, 1] (or [0, 1]).
    Determines if the event reinforces consensus or triggers polarization (backfire effect).
    """

    # --- Dynamics Parameters (The "DNA" of the event's lifecycle) ---
    # These are sampled from 'dist' modules at generation time.
    
    spatial_params: Any
    """
    Parameters governing spatial diffusion.
    Example: {'sigma': 0.1} for Gaussian decay, or {'radius': 5} for hard thresholds.
    Used by: models.spatial logic.
    """
    
    temporal_params: Any
    """
    Parameters governing temporal lifecycle.
    Example: {'decay_rate': 0.5} or {'half_life': 10}.
    Used by: models.utils (temporal decay functions).
    """

    # --- Metadata ---
    source: str = "unknown"
    """Origin of the event (e.g., 'exogenous', 'endogenous_cascade')."""
    
    meta: Dict[str, Any] = field(default_factory=dict)
    """Extra storage for debugging or visualization labels."""

    def __repr__(self):
        return (f"<Event {self.uid} | T={self.time:.1f} | L={self.loc} | "
                f"I={self.intensity:.2f} | Src={self.source}>")